# Generated by Django 4.1.5 on 2023-01-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
